name: Python Checks

on:
  # Runs at every push on main
  push:
    branches: main

  # Runs at every pull request
  pull_request:
    types: [opened, synchronize, reopened]

  # Runs at every pull request review
  pull_request_review:
    types: submitted

  # Runs manually via Run Workflow in GitHub Actions
  workflow_dispatch:

  # Runs every Monday at 12:00 UTC
  schedule:
    - cron: '0 12 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Python
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      
      # Dependencies
      - name: Install Poetry
        run: pipx install poetry
        
      - name: Install Dependencies
        run: poetry install --no-interaction --with dev

      # Format an lint
      - name: Run Lint Check
        run: make lint
