name: Tests

on:
  # Runs at every push on main
  push:
    branches: main

  # Runs at every pull request
  pull_request:
    types: [opened, synchronize, reopened]

  # Runs at every pull request review
  pull_request_review:
    types: submitted

  # Runs manually via Run Workflow in GitHub Actions
  workflow_dispatch:

  # Runs every Monday at 12:00 UTC
  schedule:
    - cron: '0 12 * * 1'

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.8.2"
  POETRY_URL: https://install.python-poetry.org
  SAMBASTUDIO_URL: ${{ secrets.SAMBASTUDIO_URL }}
  SAMBASTUDIO_API_KEY: ${{ secrets.SAMBASTUDIO_API_KEY }}
  SAMBANOVA_API_KEY: ${{ secrets.SAMBANOVA_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Python
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        id: setup_python

      # Cache and Poetry dependencies
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}
      
      - name: Install Poetry ${{ env.POETRY_VERSION }}
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      # Dependencies
      - name: Install Dependencies
        run: poetry install --no-interaction --with dev --with lint --with typing --with test

      # Unit tests
      - name: Run unit tests
        run: make tests

      # Integration tests
      - name: Run integration tests
        run: make integration_tests
